{"uuid": "a5b390e3-5e86-42e3-b40d-f3192aa2a37f", "children": ["b6b20225-1dcd-41cb-bf35-8b933d5c7cd9"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=89.0.4389.128)\n\n", "trace": "  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\workspace\\pythonselenium\\Test Sales Module POM with report\\tests\\conftest.py\", line 16, in setup\n    driver = BrowserInitialization.generateDriver(request.param, TestData.BASE_URL)\n  File \"D:\\workspace\\pythonselenium\\Test Sales Module POM with report\\utilities\\BrowserInitialization.py\", line 18, in generateDriver\n    driver.get(url)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1619084574682, "stop": 1619084580520}], "start": 1619084574682, "stop": 1619084581075}