{"uuid": "c87f7fb7-1220-412c-99b9-d158d192624c", "children": ["89d58436-8e2c-49a9-b716-e8e4408d496a"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status\nfrom disconnected: received Inspector.detached event\n  (Session info: chrome=89.0.4389.128)\n\n", "trace": "  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\workspace\\pythonselenium\\Test Sales Module POM with report\\tests\\conftest.py\", line 16, in setup\n    driver = BrowserInitialization.generateDriver('firefox', TestData.BASE_URL)\n  File \"D:\\workspace\\pythonselenium\\Test Sales Module POM with report\\utilities\\BrowserInitialization.py\", line 18, in generateDriver\n    driver.get(url)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Programs\\Odoo 12.0\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1619069522150, "stop": 1619069530287}], "start": 1619069522150, "stop": 1619069530604}